name: Production Subgraph (Mainnet)

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: graphprotocol/graph-network-subgraph/.github/workflows/template-deploy.yaml@main
    with:
      ENVIRONMENT: production
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.graphprotocol_npm_token }}
      ACCESS_TOKEN: ${{ secrets.access_token }}
